version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app/backend